##配置端口
#server:#  port: 92
##配置数据库
#spring:#  datasource:#    url: jdbc:mysql://127.0.0.1:3306/oaproject?characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
#    username: root
#    password: root
# #配置读取上传文件路径#  resources:#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/uploadFile/
##配置补全包名
#mybatis:#  type-aliases-package: com.wzw.springboot.entity
##配置mybatisMapper映射#  mapper-locations: classpath:com/wzw/springboot/mapper/*.xml
##配置打印sql语句
#logging:#  level: #    com.wzw.springboot.mapper: debug
##自定义配置上传文件服务器路径
#uploadFile: D:/uploadFile/